SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS peliculas (
    ID_movie INT UNSIGNED NOT NULL AUTO_INCREMENT,
    titulo_movie VARCHAR(255) NOT NULL,
    title_movie VARCHAR(255) DEFAULT NULL,
    original_titulo_movie VARCHAR(255) DEFAULT '',
    slug_movie VARCHAR(255) NOT NULL,
    calificacion_movie VARCHAR(20) DEFAULT '',
    duracion VARCHAR(50) DEFAULT '',
    portada_movie TEXT,
    poster_movie_2 TEXT,
    generos_movie VARCHAR(255) DEFAULT '',
    sinopsis_movie TEXT,
    enlaces_movie TEXT,
    titulo_seo VARCHAR(255) DEFAULT '',
    descripcion_seo VARCHAR(255) DEFAULT '',
    network VARCHAR(100) DEFAULT NULL,
    download TEXT,
    movieDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_movie DATE DEFAULT NULL,
    release_date DATE DEFAULT NULL,
    up_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_movie),
    UNIQUE KEY uq_peliculas_slug_movie (slug_movie)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS series (
    ID_serie INT UNSIGNED NOT NULL AUTO_INCREMENT,
    titulo_serie VARCHAR(255) NOT NULL,
    slug_serie VARCHAR(255) NOT NULL,
    sinopsis_serie TEXT,
    date_serie DATE NOT NULL,
    original_titulo_serie VARCHAR(255) DEFAULT NULL,
    poster_serie TEXT,
    portada_serie TEXT,
    generos_serie VARCHAR(255) DEFAULT '',
    network VARCHAR(100) DEFAULT NULL,
    calificacion_serie VARCHAR(20) DEFAULT '',
    temporadas_serie INT UNSIGNED DEFAULT NULL,
    titulo_seo VARCHAR(255) DEFAULT '',
    descripcion_seo VARCHAR(255) DEFAULT '',
    categoria VARCHAR(100) DEFAULT '',
    identificador_serie VARCHAR(100) DEFAULT NULL,
    serieDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    up_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID_serie),
    UNIQUE KEY uq_series_slug_serie (slug_serie)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO peliculas (
    titulo_movie,
    title_movie,
    original_titulo_movie,
    slug_movie,
    calificacion_movie,
    duracion,
    portada_movie,
    poster_movie_2,
    generos_movie,
    sinopsis_movie,
    enlaces_movie,
    titulo_seo,
    descripcion_seo,
    network,
    download,
    movieDate,
    date_movie,
    release_date
) VALUES
    (
        'Interstellar',
        'Interstellar',
        'Interstellar',
        'interstellar',
        '8.6',
        '169 min',
        'https://media.themoviedb.org/t/p/w1920_and_h800_multi_faces/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
        'https://image.tmdb.org/t/p/w600_and_h900_face/cQuuBjG78j4b2r1dFpAjnjbUplv.jpg',
        'Ciencia ficción, Drama',
        'Un grupo de exploradores viaja por un agujero de gusano en busca de un nuevo hogar para la humanidad.',
        'https://trailers.example.com/interstellar',
        'Interstellar (2014) - Película',
        'Ficha y sinopsis de Interstellar.',
        'Warner Bros.',
        'https://downloads.example.com/interstellar',
        '2024-11-01 10:00:00',
        '2014-11-07',
        '2014-11-07'
    ),
    (
        'Dune: Parte Dos',
        'Dune: Part Two',
        'Dune: Part Two',
        'dune-parte-dos',
        '8.5',
        '166 min',
        'https://images.example.com/dune2-cover.jpg',
        'https://images.example.com/dune2-poster.jpg',
        'Ciencia ficción, Aventura',
        'Paul Atreides se une a los Fremen para enfrentarse a quienes destruyeron a su familia.',
        'https://trailers.example.com/dune2',
        'Dune: Parte Dos (2024) - Película',
        'Ficha y sinopsis de Dune: Parte Dos.',
        'Legendary',
        'https://downloads.example.com/dune2',
        '2025-01-15 11:30:00',
        '2024-03-01',
        '2024-03-01'
    )
ON DUPLICATE KEY UPDATE
    titulo_movie = VALUES(titulo_movie),
    title_movie = VALUES(title_movie),
    sinopsis_movie = VALUES(sinopsis_movie),
    movieDate = VALUES(movieDate),
    date_movie = VALUES(date_movie),
    release_date = VALUES(release_date),
    up_date = CURRENT_TIMESTAMP;

INSERT INTO series (
    titulo_serie,
    slug_serie,
    sinopsis_serie,
    date_serie,
    original_titulo_serie,
    poster_serie,
    portada_serie,
    generos_serie,
    network,
    calificacion_serie,
    temporadas_serie,
    titulo_seo,
    descripcion_seo,
    categoria,
    identificador_serie,
    serieDate
) VALUES
    (
        'Breaking Bad',
        'breaking-bad',
        'Un profesor de química se convierte en fabricante de metanfetamina tras un diagnóstico terminal.',
        '2008-01-20',
        'Breaking Bad',
        'https://images.example.com/breakingbad-poster.jpg',
        'https://images.example.com/breakingbad-cover.jpg',
        'Drama, Crimen',
        'AMC',
        '9.5',
        5,
        'Breaking Bad - Serie',
        'Ficha y sinopsis de Breaking Bad.',
        'Drama',
        'bb-001',
        '2024-10-12 09:00:00'
    ),
    (
        'The Last of Us',
        'the-last-of-us',
        'Un sobreviviente y una adolescente cruzan un mundo devastado por una pandemia.',
        '2023-01-15',
        'The Last of Us',
        'https://images.example.com/tlou-poster.jpg',
        'https://images.example.com/tlou-cover.jpg',
        'Drama, Ciencia ficción',
        'HBO',
        '8.8',
        1,
        'The Last of Us - Serie',
        'Ficha y sinopsis de The Last of Us.',
        'Drama',
        'tlou-001',
        '2025-02-01 18:20:00'
    )
ON DUPLICATE KEY UPDATE
    titulo_serie = VALUES(titulo_serie),
    sinopsis_serie = VALUES(sinopsis_serie),
    date_serie = VALUES(date_serie),
    serieDate = VALUES(serieDate),
    up_date = CURRENT_TIMESTAMP;
